// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luljyhqkdpwbyujqswmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1bGp5aHFrZHB3Ynl1anFzd21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1MTc0ODUsImV4cCI6MjA4OTA5MzQ4NX0.Aob2keCGtElF_rMVlcosgC2-5QwKCmFDodEZZj-_kvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});